CDM_SCHEMA = {
    "location": {
        "location_id": {"type": "int"},
        "city": {"type": "str", "max_length": 50},
        "county": {"type": "str", "max_length": 20},
        "country_concept_id": {"type": "int", "default": 0},
        "country_source_value": {"type": "str", "max_length": 50},
        "location_source_value": {"type": "str", "max_length": 50},
    },
    "person": {
        "person_id": {"type": "int"},
        "gender_concept_id": {"type": "int", "default": 0},
        "year_of_birth": {"type": "int"},
        "month_of_birth": {"type": "int"},
        "day_of_birth": {"type": "int"},
        "birth_datetime": {"type": "datetime"},
        "race_concept_id": {"type": "int", "default": 0},
        "ethnicity_concept_id": {"type": "int", "default": 0},
        "location_id": {"type": "int"},
        "provider_id": {"type": "int"},
        "care_site_id": {"type": "int"},
        "person_source_value": {"type": "str", "max_length": 50},
        "gender_source_value": {"type": "str", "max_length": 50},
        "gender_source_concept_id": {"type": "int", "default": 0},
        "race_source_value": {"type": "str", "max_length": 50},
        "race_source_concept_id": {"type": "int", "default": 0},
        "ethnicity_source_value": {"type": "str", "max_length": 50},
        "ethnicity_source_concept_id": {"type": "int", "default": 0},
        "location_source_value": {"type": "str", "max_length": 50},
    },
    "death": {
        "death_date": {"type": "date"},
        "death_type_concept_id": {"type": "int", "default": 0},
        "death_datetime": {"type": "datetime"},
        "cause_concept_id": {"type": "int", "default": 0},
        "cause_source_value": {"type": "str", "max_length": 50},
        "cause_source_concept_id": {"type": "int", "default": 0},
        "person_source_value": {"type": "str", "max_length": 50},
    },
    "observation_period": {
        "person_source_value": {"type": "str", "max_length": 50},
        "observation_period_id": {"type": "int"},
        "observation_period_start_date": {"type": "date"},
        "observation_period_end_date": {"type": "date"},
        "period_type_concept_id": {"type": "int", "default": 0},
    },
    "care_site": {
        "care_site_id": {"type": "int"},
        "care_site_name": {"type": "str", "max_length": 255},
        "place_of_service_concept_id": {"type": "int", "default": 0},
        "care_site_source_value": {"type": "str", "max_length": 50},
        "location_source_value": {"type": "str", "max_length": 50},
    },
    "provider": {
        "provider_id": {"type": "int"},
        "gender_source_value": {"type": "str", "max_length": 50},
        "specialty_source_value": {"type": "str", "max_length": 50},
        "provider_name": {"type": "str", "max_length": 255},
        "provider_source_value": {"type": "str", "max_length": 50},
        "specialty_concept_id": {"type": "int", "default": 0},
        "gender_concept_id": {"type": "int", "default": 0},
        "care_site_source_value": {"type": "str", "max_length": 50},
    },
    "visit_occurrence": {
        "visit_occurrence_id": {"type": "int"},
        "visit_concept_id": {"type": "int", "default": 0},
        "visit_start_date": {"type": "date"},
        "visit_start_datetime": {"type": "datetime"},
        "visit_end_date": {"type": "date"},
        "visit_end_datetime": {"type": "datetime"},
        "person_source_value": {"type": "str", "max_length": 50},
        "visit_type_concept_id": {"type": "int", "default": 0},
        "visit_source_value": {"type": "str", "max_length": 50},
        "provider_source_value": {"type": "str", "max_length": 50},
        "care_site_source_value": {"type": "str", "max_length": 50},
    },
    "condition_occurrence": {
        "condition_occurrence_id": {"type": "int"},
        "person_source_value": {"type": "str", "max_length": 50},
        "condition_start_date": {"type": "date"},
        "condition_start_datetime": {"type": "datetime"},
        "condition_end_date": {"type": "date"},
        "condition_end_datetime": {"type": "datetime"},
        "condition_source_value": {"type": "str", "max_length": 50},
        "condition_source_concept_id": {"type": "int", "default": 0},
        "visit_source_value": {"type": "str", "max_length": 50},
        "condition_type_concept_id": {"type": "int", "default": 0},
    },
    "visit_detail": {
        "visit_detail_id": {"type": "int"},
        "person_source_value": {"type": "str", "max_length": 50},
        "visit_detail_concept_id": {"type": "int", "default": 0},
        "visit_detail_source_value": {"type": "str", "max_length": 50},
        "visit_detail_source_concept_id": {"type": "int", "default": 0},
        "visit_detail_start_date": {"type": "date"},
        "visit_detail_start_datetime": {"type": "datetime"},
        "visit_detail_end_date": {"type": "date"},
        "visit_detail_end_datetime": {"type": "datetime"},
        "visit_source_value": {"type": "str", "max_length": 50},
        "provider_source_value": {"type": "str", "max_length": 50},
        "visit_detail_type_concept_id": {"type": "int", "default": 0},
        "care_site_source_value": {"type": "str", "max_length": 50},
        "admitted_from_concept_id": {"type": "int", "default": 0},
        "admitted_from_source_value": {"type": "str", "max_length": 50},
    },
    "procedure_occurrence": {
        "procedure_occurrence_id": {"type": "int"},
        "person_source_value": {"type": "str", "max_length": 50},
        "procedure_date": {"type": "date"},
        "procedure_datetime": {"type": "datetime"},
        "procedure_end_date": {"type": "date"},
        "procedure_end_datetime": {"type": "datetime"},
        "procedure_type_concept_id": {"type": "int", "default": 0},
        "procedure_source_value": {"type": "str", "max_length": 50},
        "procedure_source_concept_id": {"type": "int", "default": 0},
        "visit_source_value": {"type": "str", "max_length": 50},
    },
    "drug_exposure": {
        "drug_exposure_id": {"type": "int"},
        "person_source_value": {"type": "str", "max_length": 50},
        "drug_exposure_start_date": {"type": "date"},
        "drug_exposure_start_datetime": {"type": "datetime"},
        "drug_exposure_end_date": {"type": "date"},
        "drug_exposure_end_datetime": {"type": "datetime"},
        "drug_source_value": {"type": "str", "max_length": 50},
        "drug_source_concept_id": {"type": "int", "default": 0},
        "visit_source_value": {"type": "str", "max_length": 50},
        "drug_type_concept_id": {"type": "int", "default": 0},
    },
    "measurement": {
        "measurement_id": {"type": "int"},
        "person_source_value": {"type": "str", "max_length": 50},
        "measurement_datetime": {"type": "datetime"},
        "measurement_date": {"type": "date"},
        "measurement_type_concept_id": {"type": "int", "default": 0},
        "measurement_source_value": {"type": "str", "max_length": 50},
        "measurement_source_concept_id": {"type": "int", "default": 0},
        "measurement_concept_id": {"type": "int", "default": 0},
        "value_as_number": {"type": "float"},
        "value_source_value": {"type": "str", "max_length": 50},
        "visit_source_value": {"type": "str", "max_length": 50},
        "unit_source_value": {"type": "str", "max_length": 50},
    },
    "observation": {
        "observation_id": {"type": "int"},
        "person_source_value": {"type": "str", "max_length": 50},
        "observation_datetime": {"type": "datetime"},
        "observation_date": {"type": "date"},
        "observation_type_concept_id": {"type": "int", "default": 0},
        "observation_source_value": {"type": "str", "max_length": 50},
        "observation_source_concept_id": {"type": "int", "default": 0},
        "observation_concept_id": {"type": "int", "default": 0},
        "visit_source_value": {"type": "str", "max_length": 50},
        "value_as_number": {"type": "float"},
        "value_source_value": {"type": "str", "max_length": 50},
        "unit_source_value": {"type": "str", "max_length": 50},
    },
}
